port: ${PORT}

server:
  host: 0.0.0.0
  port: ${PORT}
  path: ${WIKI_PATH}        # → /wiki

app:
  url: https://${DOMAIN}${WIKI_PATH}

db:
  type: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  pass: ${DB_PASS}
  db:   ${DB_NAME}
  ssl:  false

bindIP: 0.0.0.0
logLevel: info
devMode: false
dataPath: ./data
