port: ${PORT}

app:
  url: https://${DOMAIN}/wiki   # ← 여기에 /wiki 서브패스를 지정

db:
  type: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  pass: ${DB_PASS}
  db:   ${DB_NAME}
  ssl:  false

bindIP: 0.0.0.0
logLevel: info