services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER}"]
      interval: 2s
      timeout: 2s
      retries: 15
