services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      # .env 의 DB_USER/DB_PASS/DB_NAME 값을
      # Postgres 초기화 변수로 매핑
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:       ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 2s
      retries: 15

  wiki:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
