
services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB:       ${DB_NAME}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: "${DOCKER_HUB_USERNAME}/wikijs:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    expose:
      - "3000"      # ← 컨테이너 내부 네트워크 전용 공개

  frontend:
    image: "${DOCKER_HUB_USERNAME}/semantic-gap-ui-frontend:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    expose:
      - "80"        # ← 컨테이너 내부 네트워크 전용 공개

  nginx:
    image: nginx:latest
    restart: unless-stopped
    user: root
    depends_on:
      - wiki
      - frontend
    ports:
      - "80:80"     # ← 오직 Nginx만 호스트에 바인딩
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem:ro
      - ./ssl/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem:ro

volumes:
  db-data: