

services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB:       ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 2s
      retries: 15

  wiki:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./data:/usr/src/wiki/data
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        REACT_APP_GRAPHQL_URL: ${REACT_APP_GRAPHQL_URL}
        REACT_APP_BASE_URL:    ${REACT_APP_BASE_URL}
        REACT_APP_TOKEN:       ${REACT_APP_TOKEN}
    image: "${DOCKER_HUB_USERNAME}/semantic-gap-ui-frontend:latest"
    ports:
      - "8080:80"
