version: "3.8"

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATA_PATH: ${DATA_PATH}
    image: "${DOCKER_HUB_USERNAME:-wikijs}:${IMAGE_TAG:-latest}"
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    # 코드 커스텀 시, 호스트 폴더 마운트로 즉시 반영 가능
    volumes:
      - ./custom:/usr/src/wiki/custom
      - wiki-data:${DATA_PATH}

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - wiki
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERT_PATH}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem:ro
      - ${SSL_CERT_PATH}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem:ro

volumes:
  db-data:
  wiki-data:
