FROM node:18-alpine AS builder
WORKDIR /app


COPY package.json package-lock.json ./


RUN npm install

# 4) 소스 복사 & 빌드
COPY . .
RUN npm run build

# 5) Nginx 에 빌드 결과물 복사
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]