FROM node:16-alpine AS builder
RUN npm install -g npm@^7

WORKDIR /app


COPY package.json package-lock.json ./
RUN npm ci --production

COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]