name: CI Build, Test & Push via Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    env:
      # Docker Hub
      DOCKER_HUB_USERNAME:   ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN:      ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Wiki.js DB
      DB_USER:               ${{ secrets.DB_USER }}
      DB_PASS:               ${{ secrets.DB_PASS }}
      DB_NAME:               ${{ secrets.DB_NAME }}
      # React 빌드 시 주입할 env
      REACT_APP_GRAPHQL_URL: ${{ secrets.REACT_APP_GRAPHQL_URL }}
      REACT_APP_BASE_URL:    ${{ secrets.REACT_APP_BASE_URL }}
      REACT_APP_TOKEN:       ${{ secrets.REACT_APP_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Docker Hub login
        run: |
          echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
            | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build all images (frontend, db, wiki)
        run: |
          docker compose -f docker-compose.ci.yml build \
            --build-arg REACT_APP_GRAPHQL_URL=${REACT_APP_GRAPHQL_URL} \
            --build-arg REACT_APP_BASE_URL=${REACT_APP_BASE_URL} \
            --build-arg REACT_APP_TOKEN=${REACT_APP_TOKEN}

      - name: Start only DB
        run: docker compose -f docker-compose.ci.yml up -d db

      - name: Wait for Postgres to be ready
        run: |
          until docker compose -f docker-compose.ci.yml exec db \
            pg_isready -U "${DB_USER}" > /dev/null 2>&1; do
            echo "⏱ Waiting for Postgres…"
            sleep 2
          done

      - name: Start Wiki.js
        run: docker compose -f docker-compose.ci.yml up -d wiki

      - name: Dump generated config.yml
        run: |
          echo "=== Generated config.yml ==="
          docker compose -f docker-compose.ci.yml exec wiki \
            sh -c "cat /usr/src/wiki/config.yml"

      - name: Health‑check Wiki.js
        run: |
          until curl -s http://localhost:3000 > /dev/null; do
            echo "⏱ Waiting for Wiki.js…"
            sleep 2
          done

      - name: Smoke‑test Wiki.js API
        run: curl --fail http://localhost:3000/api/status

      - name: Tear down CI services
        run: docker compose -f docker-compose.ci.yml down --volumes

      - name: Build & tag Wiki.js Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/wikijs:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/wikijs:${{ github.sha }} \
                     ${{ secrets.DOCKER_HUB_USERNAME }}/wikijs:latest

      - name: Push Wiki.js image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wikijs:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wikijs:latest

      - name: Build & tag frontend image
        run: |
          docker tag semantic-gap-ui_frontend:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/semantic-gap-ui-frontend:${{ github.sha }}
          docker tag semantic-gap-ui_frontend:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/semantic-gap-ui-frontend:latest

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/semantic-gap-ui-frontend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/semantic-gap-ui-frontend:latest