# .github/workflows/ci.yml
name: CI Build, Test & Push via Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DB_USER:            ${{ secrets.DB_USER }}
      DB_PASS:            ${{ secrets.DB_PASS }}
      DB_NAME:            ${{ secrets.DB_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }} 

      - name: Prepare .env
        run: |
          cat > .env <<EOF
          PORT=3000
          DB_HOST=db
          DB_PORT=5432
          DB_USER=${DB_USER}
          DB_PASS=${DB_PASS}
          DB_NAME=${DB_NAME}
          EOF

      - name: Prepare data directory
        run: mkdir -p data

      - name: Build & start all services
        run: docker compose -f docker-compose.ci.yml up -d --build

      - name: Debug container status & logs
        run: |
          echo "=== Services ==="
          docker compose -f docker-compose.ci.yml ps
          echo "=== DB logs ==="
          docker compose -f docker-compose.ci.yml logs db
          echo "=== Wiki logs ==="
          docker compose -f docker-compose.ci.yml logs wiki

      - name: Health-check Wiki.js
        run: |
          curl --fail http://localhost:3000 \
            || (docker compose -f docker-compose.ci.yml logs wiki && exit 1)

      - name: Tear down services
        run: docker compose -f docker-compose.ci.yml down --volumes

      - name: Docker Hub login & push
        run: |
          echo "${{ env.DOCKER_HUB_TOKEN }}" \
            | docker login -u "${{ env.DOCKER_HUB_USERNAME }}" --password-stdin
          IMG=$(docker compose -f docker-compose.ci.yml images -q wiki)
          docker tag $IMG ${{ env.DOCKER_HUB_USERNAME }}/wikijs:${{ github.sha }}
          docker tag $IMG ${{ env.DOCKER_HUB_USERNAME }}/wikijs:latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/wikijs:${{ github.sha }}
          docker push ${{ env.DOCKER_HUB_USERNAME }}/wikijs:latest
